function HAdv(d,e,f,b){var c=document.createElement("link");c.rel="stylesheet";c.href="https://spat-cloud.github.io/data/HarScript/Advertising.css";document.head.appendChild(c);var a=document.createElement("div");a.setAttribute("style","display:none;width:100%;Height:100%;top:0;Bottom:0;Left:0;Right:0;background-color:rgba(0,0,0,0.8);position:fixed;");a.style.display="block";a.style.animation="Gb 2s 1";document.body.appendChild(a);c=document.createElement("span");c.setAttribute("style","background-color:#FFFFFF;Color:#000000;text-align:center;Left:1%;Right:1%;top:1%;bottom:20px;font-size:15px;Padding-bottom:120px;position:fixed;");
a.appendChild(c);a=document.createElement("span");a.setAttribute("style","background-Color:#9C9C9C;Color:#FFFFFF;font-size:20px;padding:12px 24px;top:0;left:0;right:0;position:absolute;");a.innerHTML="Ad";c.appendChild(a);a=document.createElement("button");a.setAttribute("style","Float:Right;Color:#000000;Font-weight:Bold;Background-Color:#9C9C9C;Border:2px Solid #000000;Border:none;padding:0;Font-size:28px;top:0;right:0;border-radius:6px;Position:absolute;");a.innerHTML="&times;";a.onclick=function(){Vf(this)};
c.appendChild(a);a=document.createElement("br");c.appendChild(a);a=document.createElement("br");c.appendChild(a);a=document.createElement("br");c.appendChild(a);a=document.createElement("br");c.appendChild(a);a=document.createElement("img");a.src=d;a.width="240";a.height="180";c.appendChild(a);d=document.createElement("p");d.style.color="#73ADEF";d.style.fontSize="14px";d.style.fontWeight="bold";d.innerHTML=e;c.appendChild(d);e=document.createElement("a");e.style.textDecoration="none";e.style.color=
"#FFFFFF";e.href=f;c.appendChild(e);f=document.createElement("button");f.setAttribute("style","color:White;Background-Image:Linear-gradient(to Bottom , Green , Lightgreen);width:100%;BOrder:None;bottom:0;Left:0;Right:0;Font-size:10px;Padding:12px;Font-weight:bold;Position:Absolute;");f.innerHTML=b;e.appendChild(f);b=document.createElement("link");b.rel="dns-prefetch";b.href="https://spat-cloud.github.io/data/HarScript/Shinchan-Movie-16-DelScene-2.webp";document.head.appendChild(b);b=document.createElement("link");
b.rel="dns-prefetch";b.href="https://spat-cloud.github.io/data/HarScript/Ads/Thumbnail 1.png";document.head.appendChild(b);b=document.createElement("link");b.rel="dns-prefetch";b.href="https://spat-cloud.github.io/data/HarScript/Ads/Deleted-Thumbnail.png";document.head.appendChild(b);b=document.createElement("link");b.rel="dns-prefetch";b.href="https://spat-cloud.github.io/data/HarScript/Ads/Buri-Buri-1.webp";document.head.appendChild(b)}
function Vf(d){d.parentElement.parentElement.style.display="none"}
function HTestAds(){setTimeout(function(){return HAdv("https://spat-cloud.github.io/data/HarScript/Shinchan-Movie-16-DelScene-2.webp","Crayon Shin chan Hero Of Kinpoko   Movie 16 2008 1080p Deleted scene  002","https://youtu.be/pkS-Q97ctOc","Watch Now For Free")},2E3);setTimeout(function(){return HAdv("https://spat-cloud.github.io/data/HarScript/Ads/Thumbnail 1.png","Crayon Shin chan Intense Battle Robo Dad Strikes Back 1080p Deleted Scene 016","https://youtu.be/kmKWVz8EoOU","Watch Now For Free")},
4E3);setTimeout(function(){return HAdv("https://spat-cloud.github.io/data/HarScript/Ads/Deleted-Thumbnail.png","Doraemon Galaxy Super Express Deleted Scene Shizuka Bathing","https://www.youtube.com/watch?v=9VJpIomle5c","Watch Now For Free")},6E3);setTimeout(function(){return HAdv("https://spat-cloud.github.io/data/HarScript/Ads/Buri-Buri-1.webp","Shinchan Movie 2 Deleted Scene","https://www.youtube.com/watch?v=yw9bcKgGEco","Watch Now For Free")},8E3);setTimeout(function(){return window.open("https://bit.ly/3xmdzxI",
"blank")},1E4)};
