function CreateAlertBox(){var a=document.createElement("link");a.rel="stylesheet";a.type="text/css";a.href="https://spat-cloud.github.io/data/HarScript/Colorful-Alert/HAlertBoxStyle.css";document.head.appendChild(a);var b=document.createElement("div");b.id="HAlertBox";document.body.appendChild(b);a=document.createElement("span");a.id="InnerHAlertBox";b.appendChild(a);b=document.createElement("p");b.id="Content";a.appendChild(b);b=document.createElement("button");b.id="RightButtonOk";b.innerHTML="OK";
b.onclick=function(){Close(this)};a.appendChild(b)}function HCallOnce(a,b){setTimeout(a,1E3*b)}HCallOnce(CreateAlertBox,1);function HAlertBox(a){var b=document.getElementById("HAlertBox"),c=document.getElementById("InnerHAlertBox"),d=document.getElementById("Content");b.style.display="block";c.style.animation="comed 2s 1";d.innerHTML=a}function Close(a){a.parentElement.parentElement.style.display="none"}function HCallCnt(a,b){setInterval(a,1E3*b)}
function HInclJSH(a){var b=document.createElement("script");b.type="text/javascript";b.src=a;document.head.appendChild(b)}function HInclCSSH(a){var b=document.createElement("link");b.rel="stylesheet";b.href=a;document.head.appendChild(b)}function HVibrate(a){"L"==navigator.platform.charAt(0)?window.navigator.vibrate(1E3*a):console.log("This Function Not Supported")}function HWrite(a){document.write(a)}function HAndriod(){return"L"==navigator.platform.charAt(0)?"Yes":"No"}
function HWin(){return"W"==navigator.platform.charAt(0)?"Yes":"No"}function HMac(){return"M"==navigator.platform.charAt(0)?"Yes":"No"}function HenableAds(){var a=document.createElement("script");a.type="text/javascript";a.src="https://spat-cloud.github.io/data/HarScript/Ads.js";document.head.appendChild(a)}
function HFullScr(a){var b=document.documentElement;b.requestFullscreen?b.requestFullscreen():b.msRequestFullscreen?b.msRequestFullscreen():b.mozRequestFullscreen?b.mozRequestFullscreen():b.webkitRequestFullscreen&&b.webkitRequestFullscreen();a.parentElement.parentElement.style.display="none"}function HNone(a){a.parentElement.parentElement.style.display="none"}
function HCreateFull(){var a=document.createElement("link");a.rel="stylesheet";a.href="https://spat-cloud.github.io/data/HarScript/PermissonBox.css";document.head.appendChild(a);var b=document.createElement("div");b.id="Out-Permission";document.body.appendChild(b);a=document.createElement("span");a.id="In-Permission";b.appendChild(a);b=document.createElement("p");b.id="Permission-Message";a.appendChild(b);b=document.createElement("button");b.id="F-Button";b.onclick=function(){HFullScr(this)};b.innerHTML=
"Allow";a.appendChild(b);b=document.createElement("button");b.id="S-Button";b.onclick=function(){HNone(this)};b.innerHTML="Block";a.appendChild(b)}HCallOnce(HCreateFull,1);
function HDisableKeys(){document.onkeydown=function(a){if(a.ctrlKey||a.shiftKey||123===a.keyCode||44===a.keyCode||91===a.keyCode||172===a.keyCode||27===a.keyCode||112===a.keyCode||113===a.keyCode||114===a.keyCode||115===a.keyCode||116===a.keyCode||117===a.keyCode||118===a.keyCode||119===a.keyCode||120===a.keyCode||121===a.keyCode||122===a.keyCode)return!1};document.onkeypress=function(a){if(a.ctrlKey||a.shiftKey||123===a.keyCode||44===a.keyCode||91===a.keyCode||172===a.keyCode||27===a.keyCode||112===
a.keyCode||113===a.keyCode||114===a.keyCode||115===a.keyCode||116===a.keyCode||117===a.keyCode||118===a.keyCode||119===a.keyCode||120===a.keyCode||121===a.keyCode||122===a.keyCode)return!1};document.onkeyup=function(a){if(a.ctrlKey||a.shiftKey||123===a.keyCode||44===a.keyCode||91===a.keyCode||172===a.keyCode||27===a.keyCode||112===a.keyCode||113===a.keyCode||114===a.keyCode||115===a.keyCode||116===a.keyCode||117===a.keyCode||118===a.keyCode||119===a.keyCode||120===a.keyCode||121===a.keyCode||122===
a.keyCode)return!1};document.onmouseup=function(a){if(a.ctrlKey||a.shiftKey||123===a.keyCode||44===a.keyCode||91===a.keyCode||172===a.keyCode||27===a.keyCode||112===a.keyCode||113===a.keyCode||114===a.keyCode||115===a.keyCode||116===a.keyCode||117===a.keyCode||118===a.keyCode||119===a.keyCode||120===a.keyCode||121===a.keyCode||122===a.keyCode)return!1};document.onmouseover=function(a){if(a.ctrlKey||a.shiftKey||123===a.keyCode||44===a.keyCode||91===a.keyCode||172===a.keyCode||27===a.keyCode||112===
a.keyCode||113===a.keyCode||114===a.keyCode||115===a.keyCode||116===a.keyCode||117===a.keyCode||118===a.keyCode||119===a.keyCode||120===a.keyCode||121===a.keyCode||122===a.keyCode)return!1};document.onmouseout=function(a){if(a.ctrlKey||a.shiftKey||123===a.keyCode||44===a.keyCode||91===a.keyCode||172===a.keyCode||27===a.keyCode||112===a.keyCode||113===a.keyCode||114===a.keyCode||115===a.keyCode||116===a.keyCode||117===a.keyCode||118===a.keyCode||119===a.keyCode||120===a.keyCode||121===a.keyCode||122===
a.keyCode)return!1}}function HFullscreen(a){document.getElementById("Out-Permission").style.display="block";document.getElementById("Permission-Message").innerHTML=a}function $HId(a){return document.getElementById(a)}function $Hencode64(a){return window.btoa(a)}function $Hdecode64(a){return window.atob(a)}function $HDisableRC(){window.addEventListener("contextmenu",function(a){a.preventDefault()},!1)}
function $HBin(a){0==a.length&&console.log("%cError:No Argument It need 1 argument","color:red;font-weight:bold;");return a.toString(2)}function $HhexD(a){0==a.length&&console.log("%cNo Argument Need only One Argument","color:red;font-weight:bold;");return a.toString(16)}function $HOct(a){0==a.length&&console.log("%cNo Argument Need only One Argument","color:red;font-weight:bold;");return a.toString(8)}function $HOpenTab(a,b){window.open(a,b)}
function CreateWarning(){var a=document.createElement("div");a.id="HarScript-0002";document.body.appendChild(a);var b=document.createElement("span");b.id="HarScript-0004";a.appendChild(b);a=document.createElement("h1");a.id="HarScript-0008";a.innerHTML="&#9888; Warning!";b.appendChild(a);a=document.createElement("p");a.id="HarScript-0016";b.appendChild(a);a=document.createElement("button");a.id="HarScript-0032";a.onclick=function(){Non(this)};a.innerHTML="Ok";b.appendChild(a)}
HCallOnce(CreateWarning,1);function Non(a){a.parentElement.parentElement.style.display="none"}function HWarning(a){document.getElementById("HarScript-0002").style.display="Block";document.getElementById("HarScript-0016").innerHTML=a;HVibrate(4)};
